AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  push
  test
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  PushFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: push/
      Layers:
        - !Ref PushLayer
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Push:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /push
            Method: post
      Environment:
        Variables:
          CMS_TOKEN: "your token"
  PushLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: push-dependencies
      Description: Dependency layer for push function
      ContentUri: dependencies/
      RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PushApi:
    Description: "API Gateway endpoint URL for Prod stage for Push  function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/push/"
  PushFunction:
    Description: "Push Lambda Function ARN"
    Value: !GetAtt PushFunction.Arn
