AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  register
  test
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  RegiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: regi/
      Layers:
        - !Ref RegiLayer
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonDynamoDBFullAccess
      - AmazonS3FullAccess
      Events:
        Regi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /regi
            Method: post
      Environment:
        Variables:
          CLIENT_ID: "your id"
          CLIENT_SECRET: "your secret"
          BUCKET_NAME: "bucket name"
          FILE_NAME: "file name"
          APP_ID: "app id"
  RegiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: regi-dependencies
      Description: Dependency layer for regi function
      ContentUri: regi/node_modules/
      RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RegiApi:
    Description: "API Gateway endpoint URL for Prod stage for Regi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/regi/"
  RegiFunction:
    Description: "Regi Lambda Function ARN"
    Value: !GetAtt RegiFunction.Arn
