name: lambda CICD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sam build
      uses: youyo/aws-sam-action/python3.8@master
      with:
        sam_command: build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
