name: lambda CICD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sam
      run: pip install aws-sam-cli >/dev/null 2>&1
    - name: sam build
      run: cd .github && bash cicd_lambda.sh 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
        SAM_CLI_TELEMETRY: 0
